### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by artrayd** [fmal/gulp-inline-source#34]
Just for test removed everything except inline soruce

Here is my code:

gulp.task('inlinesource', function () {
    return gulp.src('./app/create-full.html')
        .pipe(inlinesource())
        .pipe(gulp.dest('./out'));
});

gulp.task('default', ['inlinesource'] );

Getting this error:

events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected token: operator (<)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/newuser/Documents/projects/gift/v0.1/node_modules/inline-source/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at /Users/newuser/Documents/projects/gift/v0.1/node_modules/gulp-util/lib/PluginError.js:45:35
    at Array.forEach (native)
    at new PluginError (/Users/newuser/Documents/projects/gift/v0.1/node_modules/gulp-util/lib/PluginError.js:44:8)
    at /Users/newuser/Documents/projects/gift/v0.1/node_modules/gulp-inline-source/index.js:37:36
    at next (/Users/newuser/Documents/projects/gift/v0.1/node_modules/inline-source/lib/run.js:25:22)
    at js (/Users/newuser/Documents/projects/gift/v0.1/node_modules/inline-source/lib/js.js:31:14)
    at next (/Users/newuser/Documents/projects/gift/v0.1/node_modules/inline-source/lib/run.js:36:33)
    at context.fs.readFile (/Users/newuser/Documents/projects/gift/v0.1/node_modules/inline-source/lib/load.js:18:16)
    at tryToString (fs.js:455:3)

**Comment by mzohrab** [comment]
For anyone initially comes across with this error. Workaround: try turning off compression of files (in options). Library internally uses Uglify which is source of the error for the issue mentioned above.
